# adapted from https://github.com/dragonflydb/dragonfly-operator/blob/d28c5ac1c3bfbe13b917560bc5f22261acd6de77/config/samples/v1alpha1_dragonfly.yaml

# see crd at https://github.com/dragonflydb/dragonfly-operator/blob/d28c5ac1c3bfbe13b917560bc5f22261acd6de77/api/v1alpha1/dragonfly_types.go
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  labels:
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: dragonfly-sample
    app.kubernetes.io/part-of: dragonfly-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: dragonfly-operator
  name: dragonfly-sample
spec:
  # pin instead of using the operator default
  # defined here https://github.com/dragonflydb/dragonfly-operator/blob/d28c5ac1c3bfbe13b917560bc5f22261acd6de77/internal/resources/resources.go#L52
  image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.13.0
  replicas: 2
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 600m
      memory: 750Mi
