apiVersion: v1
kind: Service
metadata:
  name: dragonfly-lb
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: dragonfly-sample
